import { createGlobalTheme, createGlobalThemeContract } from "@vanilla-extract/css";

export const vars = createGlobalThemeContract({
  color: {
    primary: "color-primary",
    primaryLight: "color-primary-light",
    bg: "color-bg",
    surface: "color-surface",
    surfaceAlt: "color-surface-alt",
    text: "color-text",
    textMuted: "color-text-muted",
    border: "color-border",
    highlight: "color-highlight",
    highlightText: "color-highlight-text",
    success: "color-success",
    error: "color-error",
    warning: "color-warning",
    nodeIdle: "color-node-idle",
    nodeActive: "color-node-active",
    nodeCompleted: "color-node-completed",
    nodeBacktracked: "color-node-backtracked",
  },
  space: {
    xs: "space-xs",
    sm: "space-sm",
    md: "space-md",
    lg: "space-lg",
    xl: "space-xl",
    xxl: "space-xxl",
  },
  fontSize: {
    xs: "font-size-xs",
    sm: "font-size-sm",
    md: "font-size-md",
    lg: "font-size-lg",
    xl: "font-size-xl",
    xxl: "font-size-xxl",
  },
  radius: {
    sm: "radius-sm",
    md: "radius-md",
    lg: "radius-lg",
    full: "radius-full",
  },
  font: {
    body: "font-body",
    mono: "font-mono",
  },
});

createGlobalTheme(":root", vars, {
  color: {
    primary: "#6366f1",
    primaryLight: "#818cf8",
    bg: "#0f0f13",
    surface: "#1a1a24",
    surfaceAlt: "#24243a",
    text: "#e2e8f0",
    textMuted: "#94a3b8",
    border: "#2e2e48",
    highlight: "#fbbf24",
    highlightText: "#1a1a24",
    success: "#22c55e",
    error: "#ef4444",
    warning: "#f59e0b",
    nodeIdle: "#475569",
    nodeActive: "#fbbf24",
    nodeCompleted: "#22c55e",
    nodeBacktracked: "#ef4444",
  },
  space: {
    xs: "4px",
    sm: "8px",
    md: "16px",
    lg: "24px",
    xl: "32px",
    xxl: "48px",
  },
  fontSize: {
    xs: "11px",
    sm: "13px",
    md: "15px",
    lg: "18px",
    xl: "24px",
    xxl: "32px",
  },
  radius: {
    sm: "4px",
    md: "8px",
    lg: "12px",
    full: "9999px",
  },
  font: {
    body: "'Pretendard Variable', 'Pretendard', -apple-system, BlinkMacSystemFont, sans-serif",
    mono: "'Geist Mono', 'Fira Code', monospace",
  },
});
